### PR TITLE
pool+orders: add section to display orders and leases

### PR DESCRIPTION
**Pull request by jamaljsr**
This PR adds the account's orders and leases to the bottom section of the Pool page.

You are able to:
- view all orders for the active account
- filter orders to only see Open, Filled, or All
- sort orders by clicking on the table headers
- select an order to view the associated leases, if any
- sort leases by clicking on the table headers

There are still improvements that can be made, but this should be enough functionality for a functional MVP

### Screenshot
image

### CODE REVIEW

**Review by guggero — APPROVED** [review]
Looks clean, tidy and very professional with the order book look!

I'm not exactly sure how I produced this, might be an error on my side: I created an order on the CLI, refreshed the page and it showed up as submitted. I then matched the order in a batch. Afterwards the order wouldn't appear anymore, even when switching to "ALL". Also creating a new order on the CLI wouldn't help, that would also not show up anymore.

**Comment by jamaljsr** [comment]
Interesting. I havent tested this flow, but I don't see any reason why the source of the order would matter. I am just calling the `ListOrders` RPC. I'll test mixing in CLI orders to see if I can replicate. Thanks for the heads up 👍

**Comment by jamaljsr** [comment]
I've tested creating a bunch of orders using both the CLI and the UI. I am unable to reproduce the problem you ran into. Can you check your console logs to see if the data is being returned from the gRPC server? You can filter by `ListOrders` to narrow down all of the log messages.

image

**Comment by guggero** [comment]
Okay, never mind. I tried again from scratch and this time everything worked as expected. Probably something I screwed up on my end.

**Pull request merged**
